general:
  timezone: Asia/Taipei
  data_dir: ./data
  parquet_dir: ./data/parquet
  log_level: INFO
backtest:
  fee_bps: 10
  slippage_bps: 5
  rebalance_period: 1d
  initial_cash: 100000
  max_position_notional: 0.7
  allow_short: true
  symbols:
    - BTCUSDT
    - ETHUSDT
    - ALPACAUSDT
    - SOLUSDT
    - RAVEUSDT
    - ORDIUSDT
    - XRPUSDT
    - DOGEUSDT
    - MOVRUSDT
    - SIRENUSDT
    - ZECUSDT
    - 1000PEPEUSDT
    - BNXUSDT
    - HYPEUSDT
    - "\u5E01\u5B89\u4EBA\u751FUSDT"
    - ALPHAUSDT
    - BNBUSDT
    - BASEDUSDT
    - SOONUSDT
    - TAOUSDT
    - ENAUSDT
    - ADAUSDT
    - SUIUSDT
    - PORT3USDT
    - WLDUSDT
    - AVAXUSDT
    - METISUSDT
    - SAPIENUSDT
    - LINKUSDT
    - DOTUSDT
    - ENJUSDT
    - AAVEUSDT
    - FILUSDT
    - UXLINKUSDT
    - VIDTUSDT
    - SXPUSDT
    - BIOUSDT
    - AGIXUSDT
    - PAXGUSDT
    - NEARUSDT
    - PNUTUSDT
    - TRUMPUSDT
    - LINAUSDT
    - NEIROUSDT
    - MEMEFIUSDT
    - ETHWUSDT
    - LEVERUSDT
    - BCHUSDT
    - EDGEUSDT
    - NEIROETHUSDT
    - CRVUSDT
    - A2ZUSDT
    - SKYAIUSDT
    - RAREUSDT
    - IPUSDT
    - FTMUSDT
    - ARBUSDT
    - HIGHUSDT
    - TIAUSDT
    - PUMPUSDT
    - 1000SATSUSDT
    - WAVESUSDT
    - 1000SHIBUSDT
    - PENGUUSDT
    - ASTERUSDT
    - LTCUSDT
    - GIGGLEUSDT
    - FARTCOINUSDT
    - OMNIUSDT
    - YALAUSDT
    - AMBUSDT
    - BSWUSDT
    - TSTUSDT
    - OCEANUSDT
    - PIPPINUSDT
    - UNIUSDT
    - FETUSDT
    - GRIFFAINUSDT
    - TRXUSDT
    - XPLUSDT
    - STRAXUSDT
    - TAKEUSDT
    - BLESSUSDT
    - WLFIUSDT
    - SIGNUSDT
    - KSMUSDT
    - MUSDT
    - SKLUSDT
    - WIFUSDT
    - APTUSDT
    - VIRTUALUSDT
    - RENUSDT
    - 1000BONKUSDT
    - UNFIUSDT
    - TRBUSDT
    - RIVERUSDT
    - XLMUSDT
    - PENDLEUSDT
    - PRLUSDT
    - DGBUSDT
    - ONDOUSDT
    - GENIUSUSDT
    - TROYUSDT
    - AXLUSDT
    - POWERUSDT
    - MONUSDT
    - RENDERUSDT
    - ZETAUSDT
    - OPUSDT
    - HBARUSDT
    - DASHUSDT
    - HIFIUSDT
    - EULUSDT
    - XMRUSDT
    - OMUSDT
    - LDOUSDT
    - XAUTUSDT
    - STOUSDT
    - CHESSUSDT
    - 42USDT
    - BEATUSDT
    - SNTUSDT
    - GALAUSDT
    - BANDUSDT
    - MKRUSDT
    - ARIAUSDT
    - TRADOORUSDT
    - EPTUSDT
    - CLOUSDT
    - LITUSDT
    - BERAUSDT
    - LABUSDT
    - HUSDT
    - ROBOUSDT
    - TONUSDT
    - PLAYUSDT
    - TANSSIUSDT
    - DYDXUSDT
    - VVVUSDT
    - SLERFUSDT
    - CHRUSDT
    - ETCUSDT
    - BLZUSDT
    - ICPUSDT
    - APRUSDT
    - BRUSDT
    - VANAUSDT
    - BAKEUSDT
    - CHZUSDT
    - RVVUSDT
live:
  leverage: 3
  max_position_notional: 0.3
  circuit_breaker_drawdown: 0.1
  order_type: MARKET
